# Generated by Django 3.1.4 on 2021-01-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtititle', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField(max_length=50)),
                ('genre', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=300)),
                ('year', models.DateTimeField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
